name: Deploy to Hugging Face

on:
  push:
    branches: [ fresh ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r project/requirements.txt

      - name: Run tests
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: pytest tests
        working-directory: project

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "houzeyu2683@gmail.com"
          git config --global user.name "houzeyu2683"

          git clone https://houzeyu2683:$HF_TOKEN@huggingface.co/spaces/houzeyu2683/CyberS hf-space

          rsync -av --exclude='.git' ./project/ hf-space/

          cd hf-space
          git add .
          git commit -m "update from github" || echo "no changes"
          git push https://houzeyu2683:$HF_TOKEN@huggingface.co/spaces/houzeyu2683/CyberS